<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Richard A. Maestas">
<meta name="dcterms.date" content="2025-07-20">

<title>Demand Planning in the Digital-First, Post-Pandemic World - Picture-Perfect Forecasts</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-listing/list.min.js"></script>
<script src="../../site_libs/quarto-listing/quarto-listing.js"></script>
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-listing .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: [{ data: ['index'] },{ data: ['categories'] },{ data: ['listing-date-sort'] },{ data: ['listing-file-modified-sort'] }],
      
      searchColumns: [],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-listing'] = new List('listing-listing', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Demand Planning in the Digital-First, Post-Pandemic World</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/richard-maestas-cpf"><i class="bi bi-linkedin" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/richard-maestas-cpf"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/RichardMaeCPF"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://medium.com/@richardanthonymaestas"><i class="bi bi-medium" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Picture-Perfect Forecasts</h1>
            <p class="subtitle lead">Predicting Photo Book Web Traffic with Prophet</p>
                                <div class="quarto-categories">
                <div class="quarto-category">code</div>
                <div class="quarto-category">analysis</div>
                <div class="quarto-category">forecasting</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Richard A. Maestas </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 20, 2025</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Using holidays, sales price, and ad spend as predictors for clicks</p>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<p>In this demonstration, I applied Prophet in R to build a time series forecasting model that predicts daily web traffic to a personalized photo book product page. While commonly treated as a marketing metric, web traffic can serve as a powerful upstream demand signal—with meaningful implications for inventory, revenue, and operational planning.</p>
<p>By incorporating key drivers such as product pricing, monthly ad spend, and seasonal holidays, the model illustrates how external factors shape customer engagement over time. This transparent approach improves forecast accuracy and equips business users with clear insights into the levers that influence demand.</p>
<p>Signal-based forecasting like this enhances scenario planning in the S&amp;OP process. It enables teams to evaluate "what-if" scenarios—such as changes in media spend or price points—before committing resources. The framework also paves the way for forecasting downstream metrics like conversion rates, order volumes, and fulfillment needs, which are especially critical in direct-to-consumer and omnichannel environments where agility and cross-functional alignment are essential.</p>
</section>
<section id="objective" class="level3">
<h3 class="anchored" data-anchor-id="objective">Objective</h3>
<ul>
<li><p>Build a daily web traffic forecast using Prophet in R to establish a reliable upstream signal of customer interest and demand potential.</p></li>
<li><p>Quantify the impact of promotional timing, ad spend, pricing, and holidays on web traffic patterns to enhance forecast accuracy.</p></li>
<li><p>Enable scenario-based forecasting by layering in forward-looking marketing assumptions—helping ensure alignment, visibility, and documentation during the demand review and forecast consensus stages of the S&amp;OP process.</p></li>
</ul>
<p><strong>The following shows a preview of the data along with a visual of the complete web traffic trend over time:</strong></p>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Photo Book - Daily Web Traffic (Sample)</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Date </th>
   <th style="text-align:right;"> Price </th>
   <th style="text-align:right;"> Ad Spend </th>
   <th style="text-align:right;"> Holiday </th>
   <th style="text-align:right;"> Clicks </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2023-01-01 </td>
   <td style="text-align:right;"> 24.99 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 2005 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2023-01-02 </td>
   <td style="text-align:right;"> 24.99 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 894 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2023-01-03 </td>
   <td style="text-align:right;"> 24.99 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 934 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2023-01-04 </td>
   <td style="text-align:right;"> 24.99 </td>
   <td style="text-align:right;"> 9 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 979 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="isolating-key-drivers-of-web-traffic" class="level3">
<h3 class="anchored" data-anchor-id="isolating-key-drivers-of-web-traffic">Isolating Key Drivers of Web Traffic</h3>
<p>To better understand what influences web traffic, I began by evaluating each business driver—<strong>holidays</strong>, <strong>price</strong>, and <strong>ad spend</strong>—on its own. By testing each variable independently in a simple regression, we gain early insights into how strongly each factor correlates with customer engagement.</p>
<p>The visualizations below highlight the directional relationship and signal strength of each driver, helping us identify which levers are most predictive of traffic patterns before layering them into a more advanced forecasting model.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>The regression results revealed some useful insights</strong> into what drives daily web traffic. <strong>Ad spend</strong> had a clear, consistent impact on engagement—more investment led to more clicks, reaffirming marketing spend as a dependable traffic lever. While <strong>holidays</strong> showed only moderate statistical significance, they nearly doubled average daily visits during peak periods. That sharp but infrequent surge highlights the value of well-timed seasonal campaigns. In contrast, <strong>price</strong> didn't show much direct influence on click behavior, suggesting that visitors are more responsive to promotional messaging and visibility than to pricing alone.</p>
</section>
<section id="building-a-baseline-forecast" class="level3">
<h3 class="anchored" data-anchor-id="building-a-baseline-forecast">Building a Baseline Forecast</h3>
<p>With a clearer understanding of the individual drivers of web traffic, the next step is to build a baseline forecast model using Prophet. This model leverages historical trends and seasonality to predict future daily clicks without any external inputs. It serves as a starting point to evaluate how much predictive power comes from the data's natural patterns alone—before layering in business drivers like holidays, price, or ad spend.</p>
<div class="callout-note callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Prophet</strong> is an open-source library developed by Facebook for forecasting time series data. It’s available in both R and Python.&nbsp;More info can be found <a href="https://facebook.github.io/prophet/">here</a>.</p>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>The baseline forecast offers a solid foundation,</strong> accurately capturing long-term trends and seasonal dips—like the annual decline in January traffic. However, it fails to account for sharp, event-driven spikes around holidays. As a result, the model underpredicts key moments like the expected lift on Valentine's Day 2025, underscoring the need to include external drivers such as holidays to improve short-term accuracy.</p>
</section>
<section id="enhancing-the-forecast-with-holidays-and-ad-spend" class="level3">
<h3 class="anchored" data-anchor-id="enhancing-the-forecast-with-holidays-and-ad-spend">Enhancing the Forecast with Holidays and Ad Spend</h3>
<p>To improve the model's accuracy, the next step is to incorporate <strong>holiday events</strong> and <strong>monthly ad spend</strong>—two factors that have shown strong influence on web traffic. By adding these as external predictors, the model can better capture promotional spikes and the lift generated by marketing investment, resulting in a more realistic and actionable forecast.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="index_files/figure-html/forecast-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>This updated model demonstrates a meaningful improvement</strong> over the baseline. It successfully captures sharp spikes in traffic around key holidays—most notably the projected increase for Valentine's Day—and more accurately reflects patterns influenced by consistent monthly ad spend. By incorporating both seasonal events and marketing investment, the model produces a forecast that better aligns with real-world demand drivers and provides more actionable insight for planning.</p>
</section>
<section id="evaluating-forecast-accuracy" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-forecast-accuracy">Evaluating Forecast Accuracy</h3>
<p>While the visual forecasts provide helpful context, it's difficult to assess which model performs better by sight alone. To compare models objectively, we'll use <strong>cross-validation</strong>—a statistical technique that evaluates forecast accuracy by testing each model's performance on historical data.</p>
<div class="callout-note callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Cross-validation</strong> is a technique to evaluate how well a model can predict future values by using historical data. It helps determine if a model will generalize well to new, unseen data, which is essential for making accurate forecasts. With respect to time series forecasting, cross-validation preserves the chronological order of observations.&nbsp;</p>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">

<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>Forecast Model Performance Comparison</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Model </th>
   <th style="text-align:right;"> MAE </th>
   <th style="text-align:right;"> RMSE </th>
   <th style="text-align:right;"> MAPE </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Baseline Prophet </td>
   <td style="text-align:right;"> 105.269 </td>
   <td style="text-align:right;"> 154.150 </td>
   <td style="text-align:right;"> 10.68% </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Holidays &amp; Ad Spend </td>
   <td style="text-align:right;"> 82.836 </td>
   <td style="text-align:right;"> 107.618 </td>
   <td style="text-align:right;"> 8.39% </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><strong>Incorporating holidays and ad spend</strong> into the forecast model significantly improved accuracy. The enhanced model reduced the <strong>mean absolute error (MAE) by ~22%</strong>, the <strong>root mean squared error (RMSE) by ~30%</strong>, and the <strong>mean absolute percentage error (MAPE) from 10.68% to 8.39%</strong> compared to the baseline. This highlights the strong predictive value of aligning forecasts with seasonal events and marketing investment.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>This demonstration highlights how incorporating marketing inputs into time series forecasting—like ad spend, pricing, and seasonal holidays—can sharpen demand signal accuracy and unlock broader strategic value. Forecasting web traffic isn't just about measuring digital engagement; it's about uncovering intent. When modeled thoughtfully, traffic becomes an upstream demand signal—one that connects marketing strategy directly to operational planning.</p>
<p>By using a flexible, driver-based framework in Prophet, demand planners can transform historical behavior and forward-looking assumptions into actionable forecasts. Campaign shifts, price adjustments, and media budget changes are no longer vague variables—they're quantifiable inputs that shape demand expectations and guide planning decisions. In the context of S&amp;OP, this translates into more meaningful Demand Review conversations, where modeled scenarios bring cross-functional teams onto the same page with data-backed clarity.</p>
<p>Ultimately, this approach reframes the forecast not as a static report, but as a dynamic planning tool—one that links top-of-funnel engagement to downstream KPIs like conversions, order volume, and fulfillment needs. It strengthens collaboration, speeds up alignment, and gives businesses the agility to respond, adapt, and scale. The result? A forecast that doesn’t just project demand—it narrates the story behind it.</p>



</section>

<div class="quarto-listing quarto-listing-container-default" id="listing-listing">
<div class="list quarto-listing-default">

</div>
<div class="listing-no-matching d-none">
No matching items
</div>
</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>