project:
  type: website
  output-dir: docs
website:
  title: "Demand Planning in the Digital-First, Post-Pandemic World"
  google-analytics: "G-DBN6ZZWDNL"
  navbar:
    right:
      - about.qmd
      - icon: envelope
        href: mailto:richardanthonymaestas@gmail.com
      - icon: linkedin
        href: https://linkedin.com/in/richard-maestas-cpf
      - icon: github
        href: https://github.com/richard-maestas-cpf
      - icon: twitter
        href: https://twitter.com/RichardMaeCPF
      - icon: medium
        href: https://medium.com/@richardanthonymaestas
  page-footer:
    center: |
      © 2025 Richard A. Maestas, CPF
format:
  html:
    theme: cosmo
    css: styles.css
listing:
  type: default
  contents: posts
  sort: 
   - "pinned desc"
   - "date desc"
editor: visual

