project:
  type: website
  output-dir: docs
website:
  title: "Demand Planning in the Digital-First, Post-Pandemic World"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/richard-maestas-cpf
      - icon: github
        href: https://github.com/richard-maestas-cpf
      - icon: twitter
        href: https://twitter.com/RichardMaeCPF
      - icon: medium
        href: https://medium.com/@richardanthonymaestas
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

